-- customer 31: 27 events from data/valr_exports/customer_31_20260423.csv
-- customer 48: 15 events from data/valr_exports/customer_48_20260423.csv
-- customer 999: 55 events from data/valr_exports/customer_999_20260423.csv
-- ===========================================================
-- One-shot backfill: rebuild funding events + ledger lines for
-- customers 31,48,999 from VALR CSV exports.
-- Generated by scripts/backfill_from_valr_exports.py
-- Timestamp: 2026-04-23T14:18:53.749526+00:00
-- ===========================================================

BEGIN;

-- 1) Wipe existing funding/ledger/balance rows for in-scope customers
DELETE FROM lth_pvr.balances_daily       WHERE customer_id IN (31,48,999);
DELETE FROM lth_pvr.hodl_balances_daily  WHERE customer_id IN (31,48,999);
DELETE FROM lth_pvr.std_dca_balances_daily WHERE customer_id IN (31,48,999);
DELETE FROM lth_pvr.ledger_lines         WHERE customer_id IN (31,48,999) AND kind IN ('topup','withdrawal','deposit','transfer');
DELETE FROM lth_pvr.exchange_funding_events WHERE customer_id IN (31,48,999);

-- 2) Insert reconstructed funding events AND matching ledger lines.
--    The ledger lines are inserted directly (kind=topup/withdrawal)
--    rather than letting ef_post_ledger_and_balances derive them, to avoid
--    re-charging the 0.75% platform fee on historical deposits.
--    Once the matching note='funding:<uuid>' exists, the edge function will
--    skip these funding events on its next run.

WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'deposit', 'USDT', 2.0, 'VALR_C31_20260101211520_018',
          '2026-01-01T21:15:20+00:00', 'VALR_BF_VALR_C31_20260101211520_018', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-01-01', 'topup',
       0, 2.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'withdrawal', 'USDT', -2.0, 'VALR_C31_20260101215104_017',
          '2026-01-01T21:51:04+00:00', 'VALR_BF_VALR_C31_20260101215104_017', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-01-01', 'withdrawal',
       0, -2.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'deposit', 'BTC', 1e-05, 'VALR_C31_20260125114926_016',
          '2026-01-25T11:49:26+00:00', 'VALR_BF_VALR_C31_20260125114926_016', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-01-25', 'topup',
       1e-05, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'withdrawal', 'BTC', -7.83e-06, 'VALR_C31_20260126180906_015',
          '2026-01-26T18:09:06+00:00', 'VALR_BF_VALR_C31_20260126180906_015', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-01-26', 'withdrawal',
       -7.83e-06, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'deposit', 'USDT', 5.3241669946, 'VALR_C31_20260421180152_014',
          '2026-04-21T18:01:52+00:00', 'VALR_BF_VALR_C31_20260421180152_014', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       0, 5.3241669946, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'deposit', 'BTC', 6.224e-05, 'VALR_C31_20260421180201_013',
          '2026-04-21T18:02:01+00:00', 'VALR_BF_VALR_C31_20260421180201_013', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       6.224e-05, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_deposit', 'ZAR', 25.0005836, 'VALR_C31_20260421180425_012',
          '2026-04-21T18:04:25+00:00', 'VALR_BF_VALR_C31_20260421180425_012', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       0, 0, 25.0005836, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_deposit', 'ZAR', 87.605309751555, '019db190-5a47-79e4-9011-26c2701b8c3f',
          '2026-04-21T19:42:00+00:00', 'VALR_BF_019db190-5a47-79e4-9011-26c2701b8c3f_CREDIT_011', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'USDT', 'conversion_from_amount', 5.2937, 'fee_amount', 0.307695518445, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       0, 0, 87.605309751555, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'withdrawal', 'USDT', -5.2937, '019db190-5a47-79e4-9011-26c2701b8c3f',
          '2026-04-21T19:42:00+00:00', 'VALR_BF_019db190-5a47-79e4-9011-26c2701b8c3f_DEBIT_011', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 87.605309751555, 'fee_amount', 0.307695518445, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'withdrawal',
       0, -5.2937, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_deposit', 'ZAR', 12.20363960174, '019db190-5a86-77bb-a6c2-4eef7390376d',
          '2026-04-21T19:42:00+00:00', 'VALR_BF_019db190-5a86-77bb-a6c2-4eef7390376d_CREDIT_010', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'credit', 'conversion_from', 'BTC', 'conversion_from_amount', 9.82e-06, 'fee_amount', 0.04286275826, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       0, 0, 12.20363960174, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'withdrawal', 'BTC', -9.82e-06, '019db190-5a86-77bb-a6c2-4eef7390376d',
          '2026-04-21T19:42:00+00:00', 'VALR_BF_019db190-5a86-77bb-a6c2-4eef7390376d_DEBIT_010', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 12.20363960174, 'fee_amount', 0.04286275826, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'withdrawal',
       -9.82e-06, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_deposit', 'ZAR', 11.99994107067, '019db191-d2e0-7d09-88be-651e3e9d7e3a',
          '2026-04-21T19:43:37+00:00', 'VALR_BF_019db191-d2e0-7d09-88be-651e3e9d7e3a_CREDIT_009', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'credit', 'conversion_from', 'BTC', 'conversion_from_amount', 9.66e-06, 'fee_amount', 0.04214730933, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       0, 0, 11.99994107067, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'withdrawal', 'BTC', -9.66e-06, '019db191-d2e0-7d09-88be-651e3e9d7e3a',
          '2026-04-21T19:43:37+00:00', 'VALR_BF_019db191-d2e0-7d09-88be-651e3e9d7e3a_DEBIT_009', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 11.99994107067, 'fee_amount', 0.04214730933, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'withdrawal',
       -9.66e-06, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_deposit', 'ZAR', 11.922044476335, '019db193-29c4-7ad7-a8ca-054265168547',
          '2026-04-21T19:45:04+00:00', 'VALR_BF_019db193-29c4-7ad7-a8ca-054265168547_CREDIT_008', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'credit', 'conversion_from', 'BTC', 'conversion_from_amount', 9.59e-06, 'fee_amount', 0.041873713665, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       0, 0, 11.922044476335, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'withdrawal', 'BTC', -9.59e-06, '019db193-29c4-7ad7-a8ca-054265168547',
          '2026-04-21T19:45:04+00:00', 'VALR_BF_019db193-29c4-7ad7-a8ca-054265168547_DEBIT_008', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 11.922044476335, 'fee_amount', 0.041873713665, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'withdrawal',
       -9.59e-06, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_deposit', 'ZAR', 11.92192024268, '019db193-2a6d-7c1e-84cf-0ed90d26ede6',
          '2026-04-21T19:45:05+00:00', 'VALR_BF_019db193-2a6d-7c1e-84cf-0ed90d26ede6_CREDIT_007', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'credit', 'conversion_from', 'BTC', 'conversion_from_amount', 9.59e-06, 'fee_amount', 0.04187327732, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       0, 0, 11.92192024268, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'withdrawal', 'BTC', -9.59e-06, '019db193-2a6d-7c1e-84cf-0ed90d26ede6',
          '2026-04-21T19:45:05+00:00', 'VALR_BF_019db193-2a6d-7c1e-84cf-0ed90d26ede6_DEBIT_007', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 11.92192024268, 'fee_amount', 0.04187327732, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'withdrawal',
       -9.59e-06, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_deposit', 'ZAR', 11.889218929275, '019db195-9c15-797d-8f70-9826d23e5cff',
          '2026-04-21T19:47:45+00:00', 'VALR_BF_019db195-9c15-797d-8f70-9826d23e5cff_CREDIT_006', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'credit', 'conversion_from', 'BTC', 'conversion_from_amount', 9.55e-06, 'fee_amount', 0.041758420725, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       0, 0, 11.889218929275, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'withdrawal', 'BTC', -9.55e-06, '019db195-9c15-797d-8f70-9826d23e5cff',
          '2026-04-21T19:47:45+00:00', 'VALR_BF_019db195-9c15-797d-8f70-9826d23e5cff_DEBIT_006', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 11.889218929275, 'fee_amount', 0.041758420725, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'withdrawal',
       -9.55e-06, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_deposit', 'ZAR', 11.97666221284, '019db197-c124-7a8a-be07-78eb4cded1af',
          '2026-04-21T19:50:05+00:00', 'VALR_BF_019db197-c124-7a8a-be07-78eb4cded1af_CREDIT_005', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'credit', 'conversion_from', 'BTC', 'conversion_from_amount', 9.62e-06, 'fee_amount', 0.04206554716, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'topup',
       0, 0, 11.97666221284, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'withdrawal', 'BTC', -9.62e-06, '019db197-c124-7a8a-be07-78eb4cded1af',
          '2026-04-21T19:50:05+00:00', 'VALR_BF_019db197-c124-7a8a-be07-78eb4cded1af_DEBIT_005', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'BTCZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 11.97666221284, 'fee_amount', 0.04206554716, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-21', 'withdrawal',
       -9.62e-06, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_withdrawal', 'ZAR', -100.0, 'VALR_C31_20260422043746_004',
          '2026-04-22T04:37:46+00:00', 'VALR_BF_VALR_C31_20260422043746_004', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Withdraw', 'fee_amount', 0.0, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-22', 'withdrawal',
       0, 0, -100.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_deposit', 'ZAR', 100.0, 'VALR_C31_20260422050200_003',
          '2026-04-22T05:02:00+00:00', 'VALR_BF_VALR_C31_20260422050200_003', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-22', 'topup',
       0, 0, 100.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'deposit', 'BTC', 3.45384e-06, '019db66e-7b95-75fd-a9ab-ced39ad875e3',
          '2026-04-22T18:23:07+00:00', 'VALR_BF_019db66e-7b95-75fd-a9ab-ced39ad875e3_CREDIT_001', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'BTCZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 4.58748225, 'fee_amount', 5.616e-08, 'fee_asset', 'BTC'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-22', 'topup',
       3.45384e-06, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'deposit', 'BTC', 1.160136e-05, '019db66e-7b95-75fd-a9ab-ced39ad875e3',
          '2026-04-22T18:23:07+00:00', 'VALR_BF_019db66e-7b95-75fd-a9ab-ced39ad875e3_CREDIT_002', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'BTCZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 15.4062288, 'fee_amount', 1.8864e-07, 'fee_asset', 'BTC'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-22', 'topup',
       1.160136e-05, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_withdrawal', 'ZAR', -4.58748225, '019db66e-7b95-75fd-a9ab-ced39ad875e3',
          '2026-04-22T18:23:07+00:00', 'VALR_BF_019db66e-7b95-75fd-a9ab-ced39ad875e3_DEBIT_001', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'BTCZAR', 'leg', 'debit', 'conversion_to', 'BTC', 'conversion_to_amount', 3.45384e-06, 'fee_amount', 5.616e-08, 'fee_asset', 'BTC'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-22', 'withdrawal',
       0, 0, -4.58748225, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, '734cd9c0-4e6f-4510-aaa1-a088779c16bc',
          'zar_withdrawal', 'ZAR', -15.4062288, '019db66e-7b95-75fd-a9ab-ced39ad875e3',
          '2026-04-22T18:23:07+00:00', 'VALR_BF_019db66e-7b95-75fd-a9ab-ced39ad875e3_DEBIT_002', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'BTCZAR', 'leg', 'debit', 'conversion_to', 'BTC', 'conversion_to_amount', 1.160136e-05, 'fee_amount', 1.8864e-07, 'fee_asset', 'BTC'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 31, DATE '2026-04-22', 'withdrawal',
       0, 0, -15.4062288, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'deposit', 'BTC', 9.05e-06, 'VALR_C48_20260207195349_014',
          '2026-02-07T19:53:49+00:00', 'VALR_BF_VALR_C48_20260207195349_014', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Off-chain blockchain deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-07', 'topup',
       9.05e-06, 0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'deposit', 'USDT', 1.0, 'VALR_C48_20260207204318_013',
          '2026-02-07T20:43:18+00:00', 'VALR_BF_VALR_C48_20260207204318_013', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Off-chain blockchain deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-07', 'topup',
       0, 1.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'deposit', 'USDT', 10.0, 'VALR_C48_20260208165621_012',
          '2026-02-08T16:56:21+00:00', 'VALR_BF_VALR_C48_20260208165621_012', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-08', 'topup',
       0, 10.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'withdrawal', 'USDT', -0.075, 'VALR_C48_20260208170005_011',
          '2026-02-08T17:00:05+00:00', 'VALR_BF_VALR_C48_20260208170005_011', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-08', 'withdrawal',
       0, -0.075, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'withdrawal', 'USDT', -0.08249999999999999, 'VALR_C48_20260208173414_010',
          '2026-02-08T17:34:14+00:00', 'VALR_BF_VALR_C48_20260208173414_010', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-08', 'withdrawal',
       0, -0.08249999999999999, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'withdrawal', 'USDT', -10.8425, 'VALR_C48_20260208174503_009',
          '2026-02-08T17:45:03+00:00', 'VALR_BF_VALR_C48_20260208174503_009', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-08', 'withdrawal',
       0, -10.8425, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'deposit', 'USDT', 2.0, 'VALR_C48_20260208185336_008',
          '2026-02-08T18:53:36+00:00', 'VALR_BF_VALR_C48_20260208185336_008', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-08', 'topup',
       0, 2.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'deposit', 'USDT', 10.0, 'VALR_C48_20260208185718_007',
          '2026-02-08T18:57:18+00:00', 'VALR_BF_VALR_C48_20260208185718_007', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-08', 'topup',
       0, 10.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'withdrawal', 'USDT', -0.09, 'VALR_C48_20260208190008_006',
          '2026-02-08T19:00:08+00:00', 'VALR_BF_VALR_C48_20260208190008_006', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-08', 'withdrawal',
       0, -0.09, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'withdrawal', 'USDT', -11.91, 'VALR_C48_20260208190421_005',
          '2026-02-08T19:04:21+00:00', 'VALR_BF_VALR_C48_20260208190421_005', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-08', 'withdrawal',
       0, -11.91, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'zar_deposit', 'ZAR', 50.0, 'VALR_C48_20260217001314_004',
          '2026-02-17T00:13:14+00:00', 'VALR_BF_VALR_C48_20260217001314_004', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-17', 'topup',
       0, 0, 50.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'zar_deposit', 'ZAR', 75.0, 'VALR_C48_20260217001341_003',
          '2026-02-17T00:13:41+00:00', 'VALR_BF_VALR_C48_20260217001341_003', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-17', 'topup',
       0, 0, 75.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'deposit', 'USDT', 6.114576, '019c6a5f-02c9-77e1-8116-b981a344e336',
          '2026-02-17T06:52:17+00:00', 'VALR_BF_019c6a5f-02c9-77e1-8116-b981a344e336_CREDIT_002', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 99.9994164, 'fee_amount', 0.099424, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-17', 'topup',
       0, 6.114576, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'zar_withdrawal', 'ZAR', -99.9994164, '019c6a5f-02c9-77e1-8116-b981a344e336',
          '2026-02-17T06:52:17+00:00', 'VALR_BF_019c6a5f-02c9-77e1-8116-b981a344e336_DEBIT_002', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 6.114576, 'fee_amount', 0.099424, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-02-17', 'withdrawal',
       0, 0, -99.9994164, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, '2e78019d-0101-4584-9e14-95bbf72de8c9',
          'zar_withdrawal', 'ZAR', -25.0005836, 'VALR_C48_20260421180425_001',
          '2026-04-21T18:04:25+00:00', 'VALR_BF_VALR_C48_20260421180425_001', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 48, DATE '2026-04-21', 'withdrawal',
       0, 0, -25.0005836, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 25000.0, 'VALR_C999_20250922234930_037',
          '2025-09-22T23:49:30+00:00', 'VALR_BF_VALR_C999_20250922234930_037', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-09-22', 'topup',
       0, 0, 25000.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 24.645558, '01997435-61ea-7d5d-a3fd-09d985b197d6',
          '2025-09-23T02:01:44+00:00', 'VALR_BF_01997435-61ea-7d5d-a3fd-09d985b197d6_CREDIT_036', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 432.121911, 'fee_amount', 0.044442, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-09-23', 'topup',
       0, 24.645558, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -432.121911, '01997435-61ea-7d5d-a3fd-09d985b197d6',
          '2025-09-23T02:01:44+00:00', 'VALR_BF_01997435-61ea-7d5d-a3fd-09d985b197d6_DEBIT_036', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 24.645558, 'fee_amount', 0.044442, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-09-23', 'withdrawal',
       0, 0, -432.121911, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 401.80185248, '01997435-61ea-7d5d-a3fd-09d985b197d6',
          '2025-09-23T06:26:16+00:00', 'VALR_BF_01997435-61ea-7d5d-a3fd-09d985b197d6_CREDIT_034', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 7044.97680016, 'fee_amount', 0.72454752, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-09-23', 'topup',
       0, 401.80185248, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 999.39774018, '01997435-61ea-7d5d-a3fd-09d985b197d6',
          '2025-09-23T06:26:16+00:00', 'VALR_BF_01997435-61ea-7d5d-a3fd-09d985b197d6_CREDIT_035', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 17522.90052981, 'fee_amount', 1.80215982, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-09-23', 'topup',
       0, 999.39774018, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -7044.97680016, '01997435-61ea-7d5d-a3fd-09d985b197d6',
          '2025-09-23T06:26:16+00:00', 'VALR_BF_01997435-61ea-7d5d-a3fd-09d985b197d6_DEBIT_034', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 401.80185248, 'fee_amount', 0.72454752, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-09-23', 'withdrawal',
       0, 0, -7044.97680016, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -17522.90052981, '01997435-61ea-7d5d-a3fd-09d985b197d6',
          '2025-09-23T06:26:16+00:00', 'VALR_BF_01997435-61ea-7d5d-a3fd-09d985b197d6_DEBIT_035', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 999.39774018, 'fee_amount', 1.80215982, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-09-23', 'withdrawal',
       0, 0, -17522.90052981, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -1425.84, 'VALR_C999_20250923063312_033',
          '2025-09-23T06:33:12+00:00', 'VALR_BF_VALR_C999_20250923063312_033', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Send', 'fee_amount', 4.0, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-09-23', 'withdrawal',
       0, -1425.84, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 350.0, 'VALR_C999_20251006234352_032',
          '2025-10-06T23:43:52+00:00', 'VALR_BF_VALR_C999_20251006234352_032', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-10-06', 'topup',
       0, 0, 350.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 20.16354018, '0199be48-ff02-730a-ae0f-83694763b549',
          '2025-10-07T11:04:33+00:00', 'VALR_BF_0199be48-ff02-730a-ae0f-83694763b549_CREDIT_031', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 349.99962732, 'fee_amount', 0.03635982, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-10-07', 'topup',
       0, 20.16354018, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -349.99962732, '0199be48-ff02-730a-ae0f-83694763b549',
          '2025-10-07T11:04:33+00:00', 'VALR_BF_0199be48-ff02-730a-ae0f-83694763b549_DEBIT_031', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 20.16354018, 'fee_amount', 0.03635982, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-10-07', 'withdrawal',
       0, 0, -349.99962732, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -20.16, 'VALR_C999_20251007111122_030',
          '2025-10-07T11:11:22+00:00', 'VALR_BF_VALR_C999_20251007111122_030', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Send', 'fee_amount', 4.0, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2025-10-07', 'withdrawal',
       0, -20.16, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 21000.0, 'VALR_C999_20260126235410_029',
          '2026-01-26T23:54:10+00:00', 'VALR_BF_VALR_C999_20260126235410_029', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-01-26', 'topup',
       0, 0, 21000.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 9.27667188, '019bfdef-7942-76b2-aee2-a884b5830c56',
          '2026-01-27T05:44:33+00:00', 'VALR_BF_019bfdef-7942-76b2-aee2-a884b5830c56_CREDIT_028', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 149.99919336, 'fee_amount', 0.01672812, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-01-27', 'topup',
       0, 9.27667188, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -149.99919336, '019bfdef-7942-76b2-aee2-a884b5830c56',
          '2026-01-27T05:44:33+00:00', 'VALR_BF_019bfdef-7942-76b2-aee2-a884b5830c56_DEBIT_028', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 9.27667188, 'fee_amount', 0.01672812, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-01-27', 'withdrawal',
       0, 0, -149.99919336, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -0.06957504, 'VALR_C999_20260127090650_027',
          '2026-01-27T09:06:50+00:00', 'VALR_BF_VALR_C999_20260127090650_027', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-01-27', 'withdrawal',
       0, -0.06957504, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 1300.84445764, '019c041d-4e44-7579-b81a-6661f58b36a9',
          '2026-01-28T10:22:34+00:00', 'VALR_BF_019c041d-4e44-7579-b81a-6661f58b36a9_CREDIT_026', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 20850.00064784, 'fee_amount', 2.34574236, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-01-28', 'topup',
       0, 1300.84445764, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -20850.00064784, '019c041d-4e44-7579-b81a-6661f58b36a9',
          '2026-01-28T10:22:34+00:00', 'VALR_BF_019c041d-4e44-7579-b81a-6661f58b36a9_DEBIT_026', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 1300.84445764, 'fee_amount', 2.34574236, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-01-28', 'withdrawal',
       0, 0, -20850.00064784, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -59.0, 'VALR_C999_20260201113534_025',
          '2026-02-01T11:35:34+00:00', 'VALR_BF_VALR_C999_20260201113534_025', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-01', 'withdrawal',
       0, -59.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 999.0, 'VALR_C999_20260210110431_024',
          '2026-02-10T11:04:31+00:00', 'VALR_BF_VALR_C999_20260210110431_024', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Receive'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'topup',
       0, 999.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 479.644804230886, '019c473c-5bb6-7b67-bfc0-e4540d0c2198',
          '2026-02-10T11:09:19+00:00', 'VALR_BF_019c473c-5bb6-7b67-bfc0-e4540d0c2198_CREDIT_023', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'USDT', 'conversion_from_amount', 29.9191, 'fee_amount', 0.864917499114, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'topup',
       0, 0, 479.644804230886, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -29.9191, '019c473c-5bb6-7b67-bfc0-e4540d0c2198',
          '2026-02-10T11:09:19+00:00', 'VALR_BF_019c473c-5bb6-7b67-bfc0-e4540d0c2198_DEBIT_023', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 479.644804230886, 'fee_amount', 0.864917499114, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'withdrawal',
       0, -29.9191, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 209.631921948288, '019c473e-acdd-7536-bc00-7805b1ac616a',
          '2026-02-10T11:10:49+00:00', 'VALR_BF_019c473e-acdd-7536-bc00-7805b1ac616a_CREDIT_022', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'USDT', 'conversion_from_amount', 13.0752, 'fee_amount', 0.378017891712, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'topup',
       0, 0, 209.631921948288, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -13.0752, '019c473e-acdd-7536-bc00-7805b1ac616a',
          '2026-02-10T11:10:49+00:00', 'VALR_BF_019c473e-acdd-7536-bc00-7805b1ac616a_DEBIT_022', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 209.631921948288, 'fee_amount', 0.378017891712, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'withdrawal',
       0, -13.0752, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 4990.99918062753, '019c473e-acdd-7536-bc00-7805b1ac616a',
          '2026-02-10T11:11:25+00:00', 'VALR_BF_019c473e-acdd-7536-bc00-7805b1ac616a_CREDIT_021', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'USDT', 'conversion_from_amount', 311.2995, 'fee_amount', 8.99999852247, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'topup',
       0, 0, 4990.99918062753, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -311.2995, '019c473e-acdd-7536-bc00-7805b1ac616a',
          '2026-02-10T11:11:25+00:00', 'VALR_BF_019c473e-acdd-7536-bc00-7805b1ac616a_DEBIT_021', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 4990.99918062753, 'fee_amount', 8.99999852247, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'withdrawal',
       0, -311.2995, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 5490.09990032973, '019c473e-acdd-7536-bc00-7805b1ac616a',
          '2026-02-10T11:12:02+00:00', 'VALR_BF_019c473e-acdd-7536-bc00-7805b1ac616a_CREDIT_020', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'USDT', 'conversion_from_amount', 342.4295, 'fee_amount', 9.89999982027, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'topup',
       0, 0, 5490.09990032973, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -342.4295, '019c473e-acdd-7536-bc00-7805b1ac616a',
          '2026-02-10T11:12:02+00:00', 'VALR_BF_019c473e-acdd-7536-bc00-7805b1ac616a_DEBIT_020', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 5490.09990032973, 'fee_amount', 9.89999982027, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'withdrawal',
       0, -342.4295, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 4846.338532579698, '019c473e-acdd-7536-bc00-7805b1ac616a',
          '2026-02-10T11:12:41+00:00', 'VALR_BF_019c473e-acdd-7536-bc00-7805b1ac616a_CREDIT_019', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'USDT', 'conversion_from_amount', 302.2767, 'fee_amount', 8.739139810302, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'topup',
       0, 0, 4846.338532579698, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -302.2767, '019c473e-acdd-7536-bc00-7805b1ac616a',
          '2026-02-10T11:12:41+00:00', 'VALR_BF_019c473e-acdd-7536-bc00-7805b1ac616a_DEBIT_019', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Sell', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'ZAR', 'conversion_to_amount', 4846.338532579698, 'fee_amount', 8.739139810302, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'withdrawal',
       0, -302.2767, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -16016.71, 'VALR_C999_20260210111417_018',
          '2026-02-10T11:14:17+00:00', 'VALR_BF_VALR_C999_20260210111417_018', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Withdraw', 'fee_amount', 30.0, 'fee_asset', 'ZAR'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-10', 'withdrawal',
       0, 0, -16016.71, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 100.0, 'VALR_C999_20260212171624_017',
          '2026-02-12T17:16:24+00:00', 'VALR_BF_VALR_C999_20260212171624_017', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-12', 'topup',
       0, 0, 100.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 1.5343512, '019c5374-ce24-7814-9252-b4a767211c8f',
          '2026-02-12T20:04:49+00:00', 'VALR_BF_019c5374-ce24-7814-9252-b4a767211c8f_CREDIT_016', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 24.99994504, 'fee_amount', 0.0249488, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-12', 'topup',
       0, 1.5343512, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -24.99994504, '019c5374-ce24-7814-9252-b4a767211c8f',
          '2026-02-12T20:04:49+00:00', 'VALR_BF_019c5374-ce24-7814-9252-b4a767211c8f_DEBIT_016', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 1.5343512, 'fee_amount', 0.0249488, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-12', 'withdrawal',
       0, 0, -24.99994504, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 100.0, 'VALR_C999_20260213053954_015',
          '2026-02-13T05:39:54+00:00', 'VALR_BF_VALR_C999_20260213053954_015', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-13', 'topup',
       0, 0, 100.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 1.2386495, '019c55e4-e492-7f5d-9bbf-58f2cbf49a4a',
          '2026-02-13T07:26:30+00:00', 'VALR_BF_019c55e4-e492-7f5d-9bbf-58f2cbf49a4a_CREDIT_014', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Market Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 19.99987, 'fee_amount', 0.0043505, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-13', 'topup',
       0, 1.2386495, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -19.99987, '019c55e4-e492-7f5d-9bbf-58f2cbf49a4a',
          '2026-02-13T07:26:30+00:00', 'VALR_BF_019c55e4-e492-7f5d-9bbf-58f2cbf49a4a_DEBIT_014', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Market Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 1.2386495, 'fee_amount', 0.0043505, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-13', 'withdrawal',
       0, 0, -19.99987, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 1.86433814, '019c5ac2-526f-71ec-820c-d638deda3202',
          '2026-02-14T13:20:46+00:00', 'VALR_BF_019c5ac2-526f-71ec-820c-d638deda3202_CREDIT_013', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 30.00590789, 'fee_amount', 0.00336186, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'topup',
       0, 1.86433814, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -30.00590789, '019c5ac2-526f-71ec-820c-d638deda3202',
          '2026-02-14T13:20:46+00:00', 'VALR_BF_019c5ac2-526f-71ec-820c-d638deda3202_DEBIT_013', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 1.86433814, 'fee_amount', 0.00336186, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'withdrawal',
       0, 0, -30.00590789, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 4.5946896, '019c5d12-ae59-7569-8ba4-ed94b7595c36',
          '2026-02-14T16:53:51+00:00', 'VALR_BF_019c5d12-ae59-7569-8ba4-ed94b7595c36_CREDIT_012', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 74.99896892, 'fee_amount', 0.0747104, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'topup',
       0, 4.5946896, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -74.99896892, '019c5d12-ae59-7569-8ba4-ed94b7595c36',
          '2026-02-14T16:53:51+00:00', 'VALR_BF_019c5d12-ae59-7569-8ba4-ed94b7595c36_DEBIT_012', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Simple Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 4.5946896, 'fee_amount', 0.0747104, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'withdrawal',
       0, 0, -74.99896892, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -0.07931653999999999, 'VALR_C999_20260214165432_011',
          '2026-02-14T16:54:32+00:00', 'VALR_BF_VALR_C999_20260214165432_011', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'withdrawal',
       0, -0.07931653999999999, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 40.0, 'VALR_C999_20260214182648_010',
          '2026-02-14T18:26:48+00:00', 'VALR_BF_VALR_C999_20260214182648_010', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'topup',
       0, 40.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 7.15, 'VALR_C999_20260214182802_009',
          '2026-02-14T18:28:02+00:00', 'VALR_BF_VALR_C999_20260214182802_009', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'topup',
       0, 7.15, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 2.76, 'VALR_C999_20260214182848_008',
          '2026-02-14T18:28:48+00:00', 'VALR_BF_VALR_C999_20260214182848_008', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (in)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'topup',
       0, 2.76, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 1.49475, '019c5d7e-24ac-7333-8efa-3e6adb480d61',
          '2026-02-14T18:51:13+00:00', 'VALR_BF_019c5d7e-24ac-7333-8efa-3e6adb480d61_CREDIT_007', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Market Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 24.09555, 'fee_amount', 0.00525, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'topup',
       0, 1.49475, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -24.09555, '019c5d7e-24ac-7333-8efa-3e6adb480d61',
          '2026-02-14T18:51:13+00:00', 'VALR_BF_019c5d7e-24ac-7333-8efa-3e6adb480d61_DEBIT_007', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Market Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 1.49475, 'fee_amount', 0.00525, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'withdrawal',
       0, 0, -24.09555, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 1.60839966, '019c5d88-3b48-7f20-a0f6-5f09cd113a45',
          '2026-02-14T19:03:33+00:00', 'VALR_BF_019c5d88-3b48-7f20-a0f6-5f09cd113a45_CREDIT_006', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 25.89262422, 'fee_amount', 0.00290034, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'topup',
       0, 1.60839966, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -25.89262422, '019c5d88-3b48-7f20-a0f6-5f09cd113a45',
          '2026-02-14T19:03:33+00:00', 'VALR_BF_019c5d88-3b48-7f20-a0f6-5f09cd113a45_DEBIT_006', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 1.60839966, 'fee_amount', 0.00290034, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-14', 'withdrawal',
       0, 0, -25.89262422, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -3.1, 'VALR_C999_20260216152729_005',
          '2026-02-16T15:27:29+00:00', 'VALR_BF_VALR_C999_20260216152729_005', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Transfer (out)'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-16', 'withdrawal',
       0, -3.1, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'withdrawal', 'USDT', -1005.0, 'VALR_C999_20260219132309_004',
          '2026-02-19T13:23:09+00:00', 'VALR_BF_VALR_C999_20260219132309_004', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Send', 'fee_amount', 4.0, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-02-19', 'withdrawal',
       0, -1005.0, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 4000.0, 'VALR_C999_20260325234958_003',
          '2026-03-25T23:49:58+00:00', 'VALR_BF_VALR_C999_20260325234958_003', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-03-25', 'topup',
       0, 0, 4000.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_deposit', 'ZAR', 10000.0, 'VALR_C999_20260325235115_002',
          '2026-03-25T23:51:15+00:00', 'VALR_BF_VALR_C999_20260325235115_002', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Deposit'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-03-25', 'topup',
       0, 0, 10000.0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'deposit', 'USDT', 817.44604382, '019d28d5-879e-7bbe-9603-015281c92253',
          '2026-03-26T07:40:56+00:00', 'VALR_BF_019d28d5-879e-7bbe-9603-015281c92253_CREDIT_001', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'credit', 'conversion_from', 'ZAR', 'conversion_from_amount', 13990.84044845, 'fee_amount', 1.47405618, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-03-26', 'topup',
       0, 817.44604382, 0, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;
WITH ins AS (
  INSERT INTO lth_pvr.exchange_funding_events
    (funding_id, org_id, customer_id, exchange_account_id, kind, asset, amount, ext_ref, occurred_at, idempotency_key, metadata)
  VALUES (gen_random_uuid(), 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, '1da38bcb-8c24-464d-81a0-7b388f84c8b3',
          'zar_withdrawal', 'ZAR', -13990.84044845, '019d28d5-879e-7bbe-9603-015281c92253',
          '2026-03-26T07:40:56+00:00', 'VALR_BF_019d28d5-879e-7bbe-9603-015281c92253_DEBIT_001', jsonb_build_object('source', 'csv_backfill', 'tx_type', 'Limit Buy', 'pair', 'USDTZAR', 'leg', 'debit', 'conversion_to', 'USDT', 'conversion_to_amount', 817.44604382, 'fee_amount', 1.47405618, 'fee_asset', 'USDT'))
  RETURNING funding_id
)
INSERT INTO lth_pvr.ledger_lines
    (org_id, customer_id, trade_date, kind, amount_btc, amount_usdt, amount_zar, fee_btc, fee_usdt, platform_fee_btc, platform_fee_usdt, note)
SELECT 'b0a77009-03b9-44a1-ae1d-34f157d44a8b', 999, DATE '2026-03-26', 'withdrawal',
       0, 0, -13990.84044845, 0, 0, 0, 0,
       'funding:' || ins.funding_id::text
FROM ins;

COMMIT;
