create table lth_pvr.strategy_versions (
  strategy_version_id uuid not null default gen_random_uuid (),
  org_id uuid not null,
  name text not null,
  notes text null,
  momo_len integer not null default 5,
  momo_thr numeric(38, 5) not null default 0.0,
  b1 numeric(38, 5) not null,
  b2 numeric(38, 5) not null,
  b3 numeric(38, 5) not null,
  b4 numeric(38, 5) not null,
  b5 numeric(38, 5) not null,
  b6 numeric(38, 5) not null,
  b7 numeric(38, 5) not null,
  b8 numeric(38, 5) not null,
  b9 numeric(38, 5) not null,
  b10 numeric(38, 5) not null,
  b11 numeric(38, 5) not null,
  trade_fee_bps numeric(38, 5) not null default 10.0,
  contrib_fee_bps numeric(38, 5) not null default 18.0,
  created_at timestamp with time zone not null default now(),
  created_by uuid null,
  constraint strategy_versions_pkey primary key (strategy_version_id)
) TABLESPACE pg_default;