create table public.adv_dca_customer_transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  customer_id bigint not null,
  transaction_date date not null,
  signal_type text null,
  omega_buy_usd numeric not null default '0'::numeric,
  omega_buy_btc numeric not null default '0'::numeric,
  omega_sell_btc numeric not null default '0'::numeric,
  source_signal text null,
  opening_balance_usd numeric not null default '0'::numeric,
  closing_balance_usd numeric not null default '0'::numeric,
  opening_balance_btc numeric not null default '0'::numeric,
  closing_balance_btc numeric not null default '0'::numeric,
  daily_dca_usd numeric not null default '0'::numeric,
  omega_sell_usd numeric not null default '0'::numeric,
  btc_closing_price_usd numeric not null,
  sab_buy_usd numeric not null default '0'::numeric,
  sab_buy_btc numeric not null default '0'::numeric,
  date_closing date not null,
  total_dca_invested_usd numeric not null default 0,
  portfolio_value_usd numeric GENERATED ALWAYS as (
    round(
      (
        (
          COALESCE(btc_closing_price_usd, (0)::numeric) * COALESCE(closing_balance_btc, (0)::numeric)
        ) + COALESCE(closing_balance_usd, (0)::numeric)
      ),
      2
    )
  ) STORED (18, 2) null,
  total_roi_percent numeric GENERATED ALWAYS as (
    case
      when (
        COALESCE(total_dca_invested_usd, (0)::numeric) = (0)::numeric
      ) then 0.0
      else round(
        (
          (
            100.0 * (
              (
                (
                  COALESCE(btc_closing_price_usd, (0)::numeric) * COALESCE(closing_balance_btc, (0)::numeric)
                ) + COALESCE(closing_balance_usd, (0)::numeric)
              ) - COALESCE(total_dca_invested_usd, (0)::numeric)
            )
          ) / total_dca_invested_usd
        ),
        1
      )
    end
  ) STORED (18, 1) null,
  trading_year integer null,
  cagr_percent numeric GENERATED ALWAYS as (
    case
      when (
        (
          COALESCE(total_dca_invested_usd, (0)::numeric) = (0)::numeric
        )
        or (COALESCE(trading_year, 0) <= 0)
      ) then 0.0
      else round(
        (
          100.0 * (
            power(
              (
                (
                  (
                    COALESCE(btc_closing_price_usd, (0)::numeric) * COALESCE(closing_balance_btc, (0)::numeric)
                  ) + COALESCE(closing_balance_usd, (0)::numeric)
                ) / NULLIF(total_dca_invested_usd, (0)::numeric)
              ),
              (1.0 / (NULLIF(trading_year, 0))::numeric)
            ) - 1.0
          )
        ),
        1
      )
    end
  ) STORED (18, 1) null,
  constraint customer_transactions_pkey primary key (id),
  constraint customer_transactions_cust_date_unique unique (customer_id, transaction_date),
  constraint customer_transactions_customer_date_unique unique (customer_id, transaction_date),
  constraint customer_tx_cust_date_unique unique (customer_id, transaction_date),
  constraint transactions_customer_id_fkey foreign KEY (customer_id) references customer_details (customer_id) on update CASCADE,
  constraint customer_transactions_type_check check (
    (
      signal_type = any (array['buy'::text, 'sell'::text])
    )
  )
) TABLESPACE pg_default;

create index IF not exists adv_cust_txdate_idx on public.adv_dca_customer_transactions using btree (customer_id, transaction_date) TABLESPACE pg_default;

create unique INDEX IF not exists adv_upsert_uniq on public.adv_dca_customer_transactions using btree (customer_id, transaction_date, date_closing) TABLESPACE pg_default;

create index IF not exists idx_adv_txn_latest on public.adv_dca_customer_transactions using btree (
  customer_id,
  transaction_date desc,
  created_at desc,
  id desc
) TABLESPACE pg_default;

create index IF not exists idx_adv_txn_by_cust_trading_year_date on public.adv_dca_customer_transactions using btree (customer_id, trading_year, transaction_date desc) TABLESPACE pg_default;

create trigger adv_trading_year_after
after INSERT
or
update OF transaction_date,
customer_id on adv_dca_customer_transactions for EACH row
execute FUNCTION recalc_trading_years_adv ();

create trigger adv_trading_year_biu BEFORE INSERT
or
update OF transaction_date,
customer_id on adv_dca_customer_transactions for EACH row
execute FUNCTION set_trading_year_adv ();

create trigger trg_sync_customer_latest
after INSERT
or DELETE
or
update on adv_dca_customer_transactions for EACH row
execute FUNCTION sync_customer_latest_from_adv_txn ();