create table public.adv_dca_sab_thresholds (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  buy_threshold numeric not null default 0.69,
  constraint adv_dca_sth_acc_bands_thresholds_pkey primary key (id),
  constraint adv_dca_sth_acc_bands_thresholds_created_at_key unique (created_at)
) TABLESPACE pg_default;