create table public.daily_data (
  daily_data_id bigint generated by default as identity not null,
  date_closing date not null,
  btc_closing_price_usd numeric not null,
  smoothed_risk_score numeric not null,
  omega_score numeric not null,
  sab_below_neg_1sd numeric not null,
  sab_below_neg_2sd numeric not null,
  omega_on_off boolean not null default false,
  constraint daily_data_pkey primary key (daily_data_id),
  constraint daily_data_daily_data_id_key unique (daily_data_id)
) TABLESPACE pg_default;

create unique INDEX IF not exists uniq_daily_data_date on public.daily_data using btree (date_closing) TABLESPACE pg_default;