create table public.adv_dca_omega_thresholds (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  buy_threshold numeric not null default 0.11,
  sell_threshold numeric not null default 0.7,
  buy_base numeric not null default 0.01,
  sell_base numeric not null default 0.001,
  buy_step numeric not null default 0.99,
  sell_step numeric not null default 0.02,
  buy_max numeric not null default '1'::numeric,
  sell_max numeric not null default 0.27,
  buy_days_between smallint not null default '3'::smallint,
  sell_days_between smallint not null default '5'::smallint,
  constraint adv_dca_omega_thesholds_pkey primary key (id),
  constraint adv_dca_omega_thesholds_created_at_key unique (created_at),
  constraint adv_dca_omega_thesholds_id_key unique (id)
) TABLESPACE pg_default;