create table public.customer_details (
  customer_id bigint generated by default as identity not null,
  created_at timestamp without time zone not null default (now() AT TIME ZONE 'utc'::text),
  first_names text not null,
  last_name text not null,
  id_number numeric not null,
  email_address text not null,
  trade_start_date date null,
  upfront_contribution_zar numeric not null,
  recurring_contribution_frequency text not null,
  recurring_contribution_zar numeric not null,
  cellphone_number text not null,
  exchange_username text null,
  exchange_password text null,
  exchange_btc_wallet_address text null default '?'::text,
  exchange_api_key text null default '?'::text,
  exchange_api_secret text null default '?'::text,
  trading_year numeric not null default '0'::numeric,
  upfront_contribution_btc numeric not null default '0'::numeric,
  exchange_api_name text null default '?'::text,
  customer_status text null,
  org_id uuid not null,
  created_by uuid null default auth.uid (),
  constraint customer_details_pkey primary key (customer_id),
  constraint customer_details_created_by_fkey foreign KEY (created_by) references auth.users (id) on delete set null,
  constraint customer_details_org_id_fkey foreign KEY (org_id) references organizations (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists customer_details_org_id_idx on public.customer_details using btree (org_id) TABLESPACE pg_default;

create index IF not exists customer_details_created_by_idx on public.customer_details using btree (created_by) TABLESPACE pg_default;

create trigger trg_customer_details_org_immutable BEFORE
update on customer_details for EACH row
execute FUNCTION prevent_org_change ();